name: Deploy Node.js app to Azure Web App - app-TestDeploy2-230829225332

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-TestDeploy2-230829225332'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CCEB9ED233584A9B98F80A32DEA35C02 }}
          package: '.'  # Specify the path to your application files (e.g., '.' for the root directory)
